return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPre", "BufNewFile" },
	build = ":TSUpdate",
	dependencies = {
		"windwp/nvim-ts-autotag",
	},
	config = function()
		local treesitter = require("nvim-treesitter.configs")

		treesitter.setup({
			highlight = {
				enable = true,
			},
			indent = { enable = true },
			autotag = {
				enable = true,
			},
			ensure_installed = {
				"arduino",
				"bash",
				"beancount",
				"bibtex",
				"c",
				"clojure",
				"cmake",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"forth",
				"git_config",
				"gitcommit",
				"gitignore",
				"go",
				"gpg",
				"html",
				"http",
				"ini",
				"java",
				"javascript",
				"jq",
				"json",
				"latex",
				"lua",
				"luadoc",
				"make",
				"markdown_inline",
				"muttrc",
				"norg",
				"ocaml",
				"passwd",
				"python",
				"regex",
				"ssh_config",
				"supercollider",
				"tmux",
				"toml",
				"vim",
				"vimdoc",
				"yaml",
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		})
	end,
}
